# -*- coding: utf-8 -*-
"""File Permissions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sHPU2HRJsXSRNPhovgmEkBgEBm3ozjJ5
"""

print("\nUnderstanding File Permissions:")
print("1. Owner (u): User who owns the file.")
print("2. Group (g): Group with access to the file.")
print("3. Others (o): All other users.")

print("\nEach category can have:")
print(" - Read (r): Read the file.")
print(" - Write (w): Modify the file.")
print(" - Execute (x): Run the file.")

print("\nExample: 'rwxrwxr-x'")
print(" - Owner: rwx (read, write, execute)")
print(" - Group: rwx (read, write, execute)")
print(" - Others: r-x (read, execute)")